### ISSUE TITLE
ValueError: To call `multi_gpu_model` with `gpus=2`

### ISSUE THREAD

**Issue by XanderChen0530** [jiangdat/COMI#2]
Hello,
Thanks for your great tool ! It will be helpful for my microscopy images. But I can't run the test.py at this moment. I suffered from an error which may result from keras using only one GPU in my ubuntu cloud service.

Here is the error:
`
Traceback (most recent call last):
  File "test.py", line 406, in <module>
    dcgan = StarGAN()
  File "test.py", line 190, in __init__
    self.combined_hq_m = multi_gpu_model(self.combined_hq, gpus=2)
  File "/home/miniconda3/envs/COMI_HBJ/lib/python3.6/site-packages/keras/utils/multi_gpu_utils.py", line 184, in multi_gpu_model
    available_devices))
ValueError: To call `multi_gpu_model` with `gpus=2`, we expect the following devices to be available: ['/cpu:0', '/gpu:0', '/gpu:1']. However this machine only has: ['/cpu:0', '/xla_gpu:0', '/xla_cpu:0', '/gpu:0']. Try reducing `gpus`.
`

I install tensorflow-gpu 1.14.0, kerase 2.2.4, cuda 10.0. And I checked tf.test.is_gpu_available() is True; K.tensorflow_backend._get_available_gpus() return 2 gpus.

Could you help me to fix this error? I am totally for the deep learning. Many thanks.

Bests,
Xiaojun

**Comment by arakis92** [comment]
Manually you can put your GPU details:
with tf.device('/gpu:0'):  # or use '/cpu:0' for CPU
            self.combined_hq_m = self.combined_hq
